//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphanePaneli.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DUYURU
    {
        public int ID { get; set; }
        public string KATEGORI { get; set; }
        public string ICERIK { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
